site_name: SDG 11.2.1 Documentation
site_url: https://sdg-11-2-1.github.io/
repo_url: https://github.com/ONSdigital/SDG_11.2.1/
repo_name: SDG 11.2.1
theme: readthedocs
pages:
  - Home: index.md
  - Data: data.md
  - Methodology: methodology.md
  - About: about.md
